version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    volumes:
      - ./postgres/postgres_data:/var/lib/postgresql
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
    env_file:
      - ./.env
    ports:
      - 5432:5432
  web:
    build: .
    container_name: django
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - postgres
  bot:
    build: .
    container_name: tg_bot
    command: python run_pooling.py
    restart: always
    env_file:
      - ./.env
    depends_on:
      - web
    volumes:
      - .:/code

volumes:
  postgres_data: