# Generated by Django 3.2 on 2021-05-13 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='interested_in_bot_mark',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
